
spring:
   profiles:
      active: dev


---

server:
   port: 8001

spring:
   profiles: dev
   application:
      name: cloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
      url: jdbc:mysql://127.0.0.1:3306/db_cloud # 数据库名称
      username: jackli
      password: dreamli0812
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
   type-aliases-package: club.javafamily.entity # 所有Entity别名类所在包
   mapper-locations:
      - classpath:mybatis/mapper/**/*.xml # mapper映射文件

eureka:
   client: #客户端注册进eureka服务列表内
      service-url:
         defaultZone: http://node1.com:7001/eureka
   instance:
      instance-id: cloud-config-provider-dept8001
      prefer-ip-address: true #访问路径可以显示IP地址

info:
   app.name: javafamily-cloud
   commany: www.javfamily.club
   artifactId: $project.artifactId$
   version: $project.version$


---

server:
   port: 8001

spring:
   profiles: test
   application:
      name: cloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
      url: jdbc:mysql://127.0.0.1:3306/db_cloud2 # 数据库名称
      username: jackli
      password: dreamli0812
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
   type-aliases-package: club.javafamily.entity # 所有Entity别名类所在包
   mapper-locations:
      - classpath:mybatis/mapper/**/*.xml # mapper映射文件

eureka:
   client: #客户端注册进eureka服务列表内
      service-url:
         defaultZone: http://node1.com:7001/eureka
   instance:
      instance-id: cloud-config-provider-dept8001
      prefer-ip-address: true #访问路径可以显示IP地址

info:
   app.name: javafamily-cloud
   commany: www.javfamily.club
   artifactId: $project.artifactId$
   version: $project.version$